name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["Sample React CI Pipeline / Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Setup vercel cli"
        run: npm install -g vercel

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Deploy to vercel"
        run: vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
